INSERT INTO clientsystem.customers (building_number, company_name, email, office_number, street, tax_number, website) VALUES ('9', 'G1-Shop Grzegorz Świdnicki', 'g.swidnicki.biuro@gmail.com', '8', 'Traugutta', 6912488075, 'gswidnicki.com');
INSERT INTO clientsystem.customers (building_number, company_name, email, office_number, street, tax_number, website) VALUES ('15', 'Pryzmat Sp. z o.o. Sp. k.', 'biuro@pryzmat.com', '', 'Ostrowskiego', 8942994513, 'pryzmat.com');
INSERT INTO clientsystem.customers (building_number, company_name, email, office_number, street, tax_number, website) VALUES ('93', 'Hydrogeometal', 'biuro@hydro-geo-metal.pl', '', 'Skłodowskiej-Curie', 6931935325, 'hydro-geo-metal.pl');
INSERT INTO clientsystem.customers (building_number, company_name, email, office_number, street, tax_number, website) VALUES ('19', 'Kobex Sp. z o.o.', 'sekretariat@kobex.eu', '31b', 'Kopernika', 7821989934, 'kobex.eu');
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('535252088', 'Grzegorz Świdnicki', 1);
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('535252077', 'Księgowość - Anna Szkudlarek', 1);
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('713906100', 'Sekretariat', 2);
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('713906104', 'Handlowiec', 2);
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('713906120', 'Księgowość', 2);
INSERT INTO clientsystem.phones (phone_number, number_desc, customer_id) VALUES ('713906127', 'Serwis drukarek', 2);